apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ray
  region: us-west-2

nodeGroups:
  - name: ray-m5-xlarge
    instanceType: m5.4xlarge
    minSize: 1
    maxSize: 10
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
    ssh: # use existing EC2 key
      publicKeyName: your-key
    labels: {role: worker}
    tags:
      k8s.io/cluster-autoscaler/enabled: 'true'
      k8s.io/cluster-autoscaler/ray: 'owned'
